Update readme (#269)
* Fix compiler warning

'MyLambda' was identified as an executable target given the presence of a 'main.swift' file. Starting with tools version 5.4.0 executable targets should be declared as 'executableTarget()'

* Fix package dependency for swift-aws-lambda-events

The swift-aws-lambda-events repo has not yet pushed tag 0.1.0 so the build fails, see output from swift build:

Computing version for https://github.com/swift-server/swift-aws-lambda-events.git
error: Dependencies could not be resolved because no versions of 'swift-aws-lambda-events' match the requirement 0.1.0..<1.0.0 and root depends on 'swift-aws-lambda-events' 0.1.0..<1.0.0.

This commit adds the workaround mentioned in the issue for the missing tag https://github.com/swift-server/swift-aws-lambda-events/issues/3

* Fix multiple products and targets build error